### ISSUE TITLE
build fails when dest is changed

### ISSUE THREAD

**Issue by blipson89** [connectivedx/fuzzy-chainsaw#270]
## Expected Behavior

I should be able to change the `dest` directory in `package.json`

## Current Behavior

When I change the `dest` directory, I am unable to build

## Steps to Reproduce (for bugs)

1. open `package.json`
2. change the `dest` property
3. `npm run full:build`

## Context

Trying to integrate with LP for a client. I am blocked due to this issue.

## Your Environment
Windows 10

## Stack Trace
```
[09:41:39] Starting 'static:render'...
[09:41:39] 'static:render' errored after 8.43 ms
[09:41:39] Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at webpackUniversalModuleDefinition (C:\Projects\Clients\GHPWellness\website\Project.Wellness\assets\tmp\static.js:3:28)
    at Object.<anonymous> (C:\Projects\Clients\GHPWellness\website\Project.Wellness\assets\tmp\static.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Gulp.<anonymous> (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\build\static-render-factory.js:29:7)
    at module.exports (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\run-sequence\index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
[09:41:39] 'build' errored after 12 s
[09:41:39] Error in plugin 'run-sequence(static:render)'
Message:
    Cannot find module 'react'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at webpackUniversalModuleDefinition (C:\Projects\Clients\GHPWellness\website\Project.Wellness\assets\tmp\static.js:3:28)
    at Object.<anonymous> (C:\Projects\Clients\GHPWellness\website\Project.Wellness\assets\tmp\static.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Gulp.<anonymous> (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\build\static-render-factory.js:29:7)
    at module.exports (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Projects\Clients\GHPWellness\src\Project\Project.Wellness\node_modules\run-sequence\index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
```

**Comment by krambuhl** [comment]
This was resolved by the 2.0.2 release.
